services:
  app:
    container_name: codecache-app
    build: .
    ports:
      - "3100:3000"
    environment:
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=password
      - DATABASE_NAME=codecache
      - secret_key=DpHMndfxXbGxsJJhZorDYA3JjcBAfXKo
    depends_on:
      - db
    networks:
      - codeCache

  db:
    container_name: codeCache-pg-container
    image: postgres:16
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=codecache
    ports:
      - "5433:5432"
    volumes:
      - ./codeCache-pgdata:/var/lib/codeCache-postgresql/data
    networks:
      - codeCache

volumes:
  codeCache-pgdata:

networks:
  codeCache:
    name: codeCache
    driver: bridge
